spring.application.name=firstSpringApp
 server.port=3000
spring.datasource.url=mysql://localhost:3306/firstSpringApp
spring.datasource.username=root
spring.datasource.password=admin
spring.profiles.active=${ACTIVE_PROFILE:dev}
